# Generated by Django 5.0.14 on 2025-12-29 12:38

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_update_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classificationresult',
            new_name='chat_classi_topic_e906f9_idx',
            old_name='chat_class_idx',
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='conversation',
            field=models.ForeignKey(help_text='The conversation turn belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='escalation_status',
            field=models.CharField(choices=[('classified', 'Successfully Classified and Responded'), ('escalate', 'Requires Human Specialist Intervention'), ('no_response', 'Generic Acknowledgement (No Reply Sent)')], help_text='The action: classified, escalate, or no_response.', max_length=50),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='response_message',
            field=models.TextField(help_text='The final response text returned by the system.'),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='topic',
            field=models.CharField(choices=[('LAB', 'Lab Appointments/Results'), ('TWIN_APPOINTMENT', 'Non-Lab Twin Health Appointments'), ('OTHERS', 'None of the Above / Escalation')], help_text='The classification: LAB, TWIN_APPOINTMENT, or OTHERS.', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(db_index=True, default=chat.models.generate_uuid, help_text='Unique identifier for the chat session, usually a UUID.', max_length=255, unique=True),
        ),
    ]
